import '@mantine/core/styles.css';
import type { Metadata } from "next";
import { Inter } from "next/font/google";
// import "./globals.css";
import { MantineProvider, ColorSchemeScript } from '@mantine/core';
import { createTheme } from '@mantine/core';

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

const theme = createTheme({
  
});

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
      <ColorSchemeScript />
      </head>
      <body >
      <MantineProvider theme={theme}>{children}</MantineProvider>
        </body>
    </html>
  );
}
